### ISSUE TITLE
[VOTE] Heroku?

### ISSUE THREAD

**Issue by Cats-United** [CatsUnitedComputers/Cats-Site#9]
Should I switch to [Heroku](https://www.heroku.com) so i can use Python?

**Comment by Firedrake969** [comment]
http://onstartups.com/tabid/3339/bid/20493/Why-PHP-Is-Fun-and-Easy-But-Python-Is-Marriage-Material.aspx
http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/
http://webonastick.com/php.html

**Comment by Cats-United** [comment]
Problems:

1. I can't get a site set up for it.
2. A lot of things need money.

**Comment by Firedrake969** [comment]
https://www.reddit.com/r/PHP/comments/1fy71s/why_do_so_many_developers_hate_php/

**Comment by Firedrake969** [comment]
You have to learn to use the terminal.

**Comment by Firedrake969** [comment]
https://devcenter.heroku.com/articles/getting-started-with-django

**Comment by Cats-United** [comment]
I user cmder too, but I'll close this for now.
